config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"
  devise_for :users

  get "home/about"=>"homes#about"
  get "search" => "searches#search"

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @book_favorite = current_user.favorites.new(book_id: @book.id)
    @book_favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    @book_favorite = current_user.favorites.find_by(book_id: @book.id)
    @book_favorite.destroy
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorites.html.erb
          <% if book.favorited_by?(current_user) %>
              <%= link_to book_favorites_path(book_id:book.id), method: :delete, remote: true do %>
                ♥<%= book.favorites.count %>
              <% end %>
            <% else %>
              <%= link_to book_favorites_path(book_id:book.id), method: :post, remote: true do %>
                ♡<%= book.favorites.count %>
              <% end %>
          <% end %>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorites", book: @book) %>");

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorites", book: @book) %>");